export const sample_foods = [
  {
    id: '1',
    name: 'Atta',
    price: 10,
    favorite: false,
    stars: 4.5,
    imageUrl: "uploads/img1.webp", 
    tags: ['Confectionary Items'],
  },
  {
    id: '2',
    name: 'Mango',
    price: 20,
    favorite: true,
    stars: 5,
    imageUrl: 'uploads/img2.jpeg',
    tags: ['Fruit'],
  },
  {
    id: '3',
    name: 'Cetaphil',
    price: 5,
    favorite: false,
    stars: 3.5,
    imageUrl: 'uploads/img3.jpeg',
    tags: ['Confectionary Item'],
  },
  {
    id: '4',
    name: 'Potato',
    price: 2,
    favorite: true,
    stars: 3,
    imageUrl: 'uploads/img4.jpeg',
    tags: ['Vegetable'],
  },
  {
    id: '5',
    name: 'Apple',
    price: 11,
    favorite: false,
    stars: 3.5,
    imageUrl: 'uploads/img5.jpeg',
    tags: ['Fruit'],
  },
  {
    id: '6',
    name: 'Brocolli',
    price: 9,
    favorite: false,
    stars: 4.0,
    imageUrl: 'uploads/img6.jpeg',
    tags: ['Vegetable'],
  },
];

export const sample_tags = [
  { name: 'All', count: 6 },
  { name: 'Confectionary Items', count: 4 },
  { name: 'Vegetable', count: 2 },
  { name: 'Fruits', count: 3 },
  { name: 'Atta', count: 2 },
  { name: 'Potato', count: 1 },
  { name: 'Apple', count: 1 },
  { name: 'Cetaphil', count: 1 },
];

export const sample_users = [
  {
    id: 1,
    name: 'Vanshika Koli',
    email: 'van@gmail.com',
    password: '12345',
    address: '#113/20 Ambala',
    isAdmin: false,
  },
  {
    id: 2,
    name: 'Uday Aggarwal',
    email: 'uday17@gmail.com',
    password: '12345',
    address: 'Sector 20 Delhi',
    isAdmin: true,
  },
];
